app/build.gradle, app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/SignupManager.java, app/src/main/java/nu/yona/app/api/manager/impl/SignupManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/manager/network/SignupNetworkImpl.java, app/src/main/java/nu/yona/app/api/model/RegisterUser.java, app/src/main/java/nu/yona/app/customview/YonaFontUtils.java, app/src/main/java/nu/yona/app/state/EventChangeListener.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/utils/PreferenceConstant.java, app/src/main/res/layout/signup_layout.xml, app/src/main/res/layout/signup_stepone_fragment.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/test/java/nu/yona/app/ui/LaunchActivityTest.java, app/src/test/java/nu/yona/app/ui/signup/StepOneTest.java
Step one for registration with Unit test.
=> Step One for registration

app/src/main/java/nu/yona/app/api/manager/impl/SignupManagerImpl.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/res/drawable/triangle_shadow.xml, app/src/main/res/layout/bottom_tab_item.xml, app/src/main/res/layout/launch_layout.xml, app/src/main/res/layout/profile_fragment.xml, app/src/main/res/layout/signup_layout.xml, app/src/main/res/layout/signup_stepone_fragment.xml, app/src/main/res/layout/signup_steptwo_fragment.xml, app/src/main/res/layout/toolbar.xml
=> UI Design Update

app/src/main/java/nu/yona/app/api/manager/AuthenticateManager.java, app/src/main/java/nu/yona/app/api/manager/dao/AuthenticateDAO.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaBuddies.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaGoals.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaUser.java, app/src/main/java/nu/yona/app/api/model/Links_.java, app/src/main/java/nu/yona/app/api/model/YonaAppActivity.java, app/src/main/java/nu/yona/app/api/model/YonaBuddies.java, app/src/main/java/nu/yona/app/api/model/YonaBuddy.java, app/src/main/java/nu/yona/app/api/model/YonaDailyActivityReports.java, app/src/main/java/nu/yona/app/api/model/YonaGoals.java, app/src/main/java/nu/yona/app/api/model/YonaLinks.java, app/src/main/java/nu/yona/app/api/model/YonaMessages.java, app/src/main/java/nu/yona/app/api/model/YonaNewDeviceRequest.java, app/src/main/java/nu/yona/app/api/model/YonaUser.java, app/src/main/java/nu/yona/app/api/model/YonaWeeklyActivityReports.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/res/values/integers.xml, app/src/test/java/nu/yona/app/api/manager/impl/AuthenticateManagerImplTest.java
API implementation for sms validation
=> API implementation for sms validation

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/PasscodeManagerImpl.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/pincode/LoggedInActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/utils/PreferenceConstant.java
Update flow of signup , to redirect user on proper screen where he has left after completed some steps,
=>  Fixed passcode was not stored properly

app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/api/manager/dao/AuthenticateDAO.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/model/User.java, app/src/main/java/nu/yona/app/customview/CustomAlertDialog.java, app/src/main/java/nu/yona/app/ui/BaseActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/java/nu/yona/app/ui/pincode/YonaPasswordTransformationManager.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/layout/blank_container_layout.xml, app/src/main/res/layout/challenges_layout.xml, app/src/main/res/layout/custom_tab_layout.xml, app/src/main/res/layout/pincode_layout.xml, app/src/main/res/layout/signup_steptwo_fragment.xml, app/src/main/res/layout/toolbar.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/dimens.xml, app/src/test/java/nu/yona/app/api/manager/impl/AuthenticateManagerImplTest.java, app/src/zdev/res/values/bool.xml, app/src/zdevelopment/res/values/bool.xml, app/src/zproduction/res/values/bool.xml
=> Added Tabs for challenges

app/src/main/java/nu/yona/app/ui/signup/StepTwo.java
=> Number validation update

app/src/main/java/nu/yona/app/api/model/RegisterUser.java
Nickname capital char issue resolved.
=> Nickname capital char issue

app/src/main/java/nu/yona/app/api/db/DBConstant.java, app/src/main/java/nu/yona/app/api/db/DBHelper.java, app/src/main/java/nu/yona/app/api/manager/dao/ActivityCategoriesDAO.java, app/src/main/java/nu/yona/app/api/manager/dao/AuthenticateDAO.java, app/src/main/java/nu/yona/app/api/manager/dao/BaseDAO.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityCategoriesNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/api/manager/network/DeviceNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/Cury.java, app/src/main/java/nu/yona/app/api/model/Embedded.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaBuddies.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaGoals.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaUser.java, app/src/main/java/nu/yona/app/api/model/ErrorMessage.java, app/src/main/java/nu/yona/app/api/model/Href.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/api/model/Links_.java, app/src/main/java/nu/yona/app/api/model/NewDeviceRequest.java, app/src/main/java/nu/yona/app/api/model/OTPVerficationCode.java, app/src/main/java/nu/yona/app/api/model/User.java, app/src/main/java/nu/yona/app/api/model/VpnProfile.java, app/src/main/java/nu/yona/app/api/model/YonaBuddies.java, app/src/main/java/nu/yona/app/api/model/YonaBuddy.java, app/src/main/java/nu/yona/app/api/model/YonaGoal.java, app/src/main/java/nu/yona/app/api/model/YonaGoals.java, app/src/main/java/nu/yona/app/api/model/YonaLinks.java, app/src/main/java/nu/yona/app/api/model/YonaUser.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java
Create Network and storing layer for Activity Category
=> APPDEV-133

app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/res/layout/login_activity.xml
=> APPDEV-131

app/src/main/res/values/strings.xml
Spelling mistake on 4-Doe mee step 2
=> APPDEV-111

app/src/main/java/nu/yona/app/api/model/EmbeddedGoals.java, app/src/main/java/nu/yona/app/api/model/Goals.java, app/src/main/java/nu/yona/app/api/model/YonaGoal.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/res/drawable/triangle_shadow_mango.xml
addded navigation bar for settings
=> updated model class of goals

app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/res/layout/login_activity.xml, app/src/main/res/values/strings.xml
Not proper Error Message - InLoggin.
=> APPDEV-143

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java
API implementation for verify PIN on server
=> APPDEV-151

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/res/layout/signup_layout.xml, app/src/main/res/layout/toolbar.xml
=> UI Improvement changes

app/src/main/java/nu/yona/app/api/manager/AuthenticateManager.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/MobileNumber.java, app/src/main/java/nu/yona/app/api/utils/ServerErrorCode.java
API implementation for requestUserOverride
=> APPDEV-154

app/src/main/java/nu/yona/app/api/manager/ChallengesManager.java, app/src/main/java/nu/yona/app/api/manager/GoalManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/GoalManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/GoalNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/PostBudgetYonaGoal.java, app/src/main/java/nu/yona/app/api/model/PostTimeZoneYonaGoal.java, app/src/main/java/nu/yona/app/api/model/PostYonaGoal.java, app/src/main/java/nu/yona/app/ui/challenges/BaseGoalCreateFragment.java, app/src/main/java/nu/yona/app/ui/challenges/TimeZoneGoalViewHolder.java
API implementation for Goals
- Post Goals
- Get Goals
- Delete Goals
=> APPDEV-157

app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/ui/tour/TourView.java
fixed: Carrousel move to next activity after last page swipe only.
=> APPDEV-148

app/build.gradle, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/PinResetDelay.java, app/src/main/java/nu/yona/app/customview/CustomTimePickerDialog.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/challenges/BaseGoalCreateFragment.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values/strings.xml, app/src/test/java/nu/yona/app/ui/LaunchActivityTest.java, build.gradle
Show Alert to user with time delay provided by server in response
=> APPDEV-182

app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/res/values/strings.xml
Show Option of Unregister in Settings
=> APPDEV-195

app/src/main/java/nu/yona/app/api/manager/impl/ActivityCategoryManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/DeviceManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/GoalManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/GoalNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/customview/CustomAlertDialog.java, app/src/main/java/nu/yona/app/customview/ViewPagerIndicator.java, app/src/main/java/nu/yona/app/listener/DataLoader.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/BaseActivity.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsFragment.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/java/nu/yona/app/ui/tour/TourView.java, app/src/main/java/nu/yona/app/utils/ApiList.java, app/src/main/res/values/strings.xml
- Removed unnecessary code
- Added comments where require.
- Handled url validation before API request.
- Code improvement for better performance.
=> Code Improvement

app/build.gradle, app/src/main/java/nu/yona/app/api/manager/ChallengesManager.java, app/src/main/java/nu/yona/app/api/manager/dao/GoalDAO.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/customview/CustomTimePickerDialog.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesFragment.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/challenges/CreditFragment.java, app/src/main/java/nu/yona/app/ui/challenges/GoalListAdapter.java, app/src/main/java/nu/yona/app/ui/challenges/OnItemClickListener.java, app/src/main/java/nu/yona/app/ui/challenges/TimeZoneGoalViewHolder.java, app/src/main/java/nu/yona/app/ui/challenges/TimeZoneGoalsAdapter.java, app/src/main/java/nu/yona/app/ui/challenges/ZoneFragment.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/drawable/circle_counter.xml, app/src/main/res/layout/custom_tab_layout.xml, app/src/main/res/layout/numberpicker_dialog.xml, app/src/main/res/layout/timezoen_goal_item_layout.xml, app/src/main/res/layout/toolbar.xml, app/src/main/res/values/strings.xml, app/src/test/java/nu/yona/app/ui/LaunchActivityTest.java, build.gradle
Fixed : onClick of button Challenge opslaan application getting crash, Implemented APPDEV 68, and 69
=> Fixed: numbers of Goal Counter not displaying

app/build.gradle, app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/dao/ActivityCategoriesDAO.java, app/src/main/java/nu/yona/app/api/manager/dao/AuthenticateDAO.java, app/src/main/java/nu/yona/app/api/manager/dao/BaseDAO.java, app/src/main/java/nu/yona/app/api/manager/dao/GoalDAO.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityCategoryManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/DeviceManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/GoalManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/api/manager/network/DeviceNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/GoalNetworkImpl.java, app/src/main/java/nu/yona/app/customview/CustomProgressDialog.java, app/src/main/java/nu/yona/app/customview/CustomTimePickerDialog.java, app/src/main/java/nu/yona/app/customview/YonaFontUtils.java, app/src/main/java/nu/yona/app/listener/YonaCustomCrashManagerListener.java, app/src/main/java/nu/yona/app/ui/BaseActivity.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/ui/tour/TourView.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values/strings.xml, app/src/zdev/res/values/strings.xml, app/src/zdevelopment/res/values/strings.xml, app/src/zproduction/res/values/strings.xml
Exception Handling through out application.
- On development environment, it will show in logs.
- On QA/Production environment, it will send report on hockey.
=> Exception Handling

app/src/main/java/nu/yona/app/customview/YonaFontUtils.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
=> Font Name update

YONA-Automation/Yona-MobileAutomation/features/step_definitions/step_definitions_singup.rb
Fixed signup script to generate random mobile number
=> Fixed signup script

YONA-Automation/Yona-MobileAutomation/features/support/mobile/platform/capabilities.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/common/EmailFetch.rb
Fixed email fetch and Capabilities script
=> Fixed Email fetchscript

app/src/main/java/nu/yona/app/ui/tour/TourView.java, app/src/main/res/layout/tour_page.xml
Text Getting Overlapped on Welkom Carousel
=> APPDEV-156

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/ChallengesManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/PasscodeManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/NetworkConstant.java, app/src/main/java/nu/yona/app/customview/CustomAlertDialog.java, app/src/main/java/nu/yona/app/customview/CustomTimePickerDialog.java, app/src/main/java/nu/yona/app/customview/YonaFontEditTextView.java, app/src/main/java/nu/yona/app/customview/YonaPhoneWatcher.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/challenges/TimeZoneGoalsAdapter.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values/strings.xml
Resolved: the app is locked, a keyboard is shown, but input is not possible.
=> APPDEV-110

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Quick Fix for Error Message and flow
=> Quick Fix for Error Message and flow

app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/customview/YonaPhoneWatcher.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/res/layout/add_friend_manually_fragment.xml, app/src/main/res/layout/login_activity.xml, app/src/main/res/layout/signup_stepone_fragment.xml, app/src/main/res/layout/signup_steptwo_fragment.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
=> UI improvements

app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java
After User Enter Invalid pin and then clicks back button, User is taken to NOGO screen
=> Back Issue in PinActivity

app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/challenges/BaseGoalCreateFragment.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesFragment.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/challenges/GoalCategoryListAdapter.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Counter not updating at syncing with two devices,
fixed crash and now updatin goal's name on list,
updated title of goal detail page
=> fixed changes

app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/challenges/BaseGoalCreateFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/layout/settings_fragment.xml, app/src/main/res/values/android-strings.xml
Minor fixes
- Added app environment in settings.
- Removed unnecessary code.
=> Minor fixes

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/res/layout/toolbar.xml, app/src/zacceptance/res/values/bool.xml, app/src/zdev/res/values/bool.xml, app/src/zdevelopment/res/values/bool.xml, app/src/zproduction/res/values/bool.xml
-Implemented strictMode (Ref: http://developer.android.com/reference/android/os/StrictMode.html)
- Updated deprecated method in Theme
=> Implemented StrictMode

app/src/main/java/nu/yona/app/api/manager/APIManager.java, app/src/main/java/nu/yona/app/api/manager/NotificationManager.java, app/src/main/java/nu/yona/app/api/manager/dao/BaseDAO.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/NotificationNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/Embedded.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/api/model/MessageBody.java, app/src/main/java/nu/yona/app/api/model/Page.java, app/src/main/java/nu/yona/app/api/model/Properties.java, app/src/main/java/nu/yona/app/api/model/YonaMessage.java, app/src/main/java/nu/yona/app/api/model/YonaMessages.java, app/src/main/java/nu/yona/app/api/utils/ServerErrorCode.java, app/src/main/java/nu/yona/app/enums/NotificationEnum.java, app/src/main/res/layout/toolbar.xml
API implementation for Notification/Messages
- get /users/{userID}/messages
- delete /users/{userID}/messages/{id}
- post /users/{userID}/messages/{id}/{messageAction}
=> APPDEV-278

app/build.gradle, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/model/Embedded.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/api/model/MessageBody.java, app/src/main/java/nu/yona/app/api/model/YonaMessage.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesFragment.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/layout/message_layout.xml, app/src/main/res/layout/toolbar.xml, app/src/main/res/values/dimens.xml
=> APPDEV-280

app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/profile/BaseProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Implement Profile Image Picker
- User can choose image from sd card or s/he can capture image from camera.
=> APPDEV-285

app/src/main/java/nu/yona/app/enums/IntentEnum.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/settings/PrivacyFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/res/layout/privacy_fragment.xml
Created blank privacy policy page
=> APPDEV-288

app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/res/layout/profile_details_fragment.xml
Update UI as per zeplin after discussion with Ben & Bert for first name and last name should have different fields.
=> APPDEV-217

app/src/main/java/nu/yona/app/api/manager/PasscodeManager.java, app/src/main/java/nu/yona/app/enums/IntentEnum.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/layout/pincode_layout.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/integers.xml, app/src/main/res/values/strings.xml
=> APPDEV-289

app/docs/nu/yona/app/enums/FriendStatusEnum.html, app/src/main/java/nu/yona/app/api/manager/impl/BuddyManagerImpl.java, app/src/main/java/nu/yona/app/enums/NotificationEnum.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/enums/StatusEnum.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Implement logic for type and status mapping
=> APPDEV-291

app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/AuthenticateManager.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/challenges/BaseGoalCreateFragment.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesFragment.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/profile/BaseProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java, app/src/main/java/nu/yona/app/ui/settings/PrivacyFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/res/layout/profile_details_fragment.xml, app/src/main/res/layout/profile_fragment.xml
API implementation for update user profile
=> APPDEV-284

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendFragment.java, app/src/main/java/nu/yona/app/ui/profile/BaseProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/layout/profile_details_fragment.xml, app/src/main/res/layout/profile_fragment.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
- Friends Profile View
- Updated Contact book permission flow.
=> APPDEV-292

YONA-Automation/Yona-MobileAutomation/features/Add_device.feature, YONA-Automation/Yona-MobileAutomation/features/SinguptoYona.feature, YONA-Automation/Yona-MobileAutomation/features/step_definitions/step_defination_add_device.rb, YONA-Automation/Yona-MobileAutomation/features/step_definitions/step_definitions_singup.rb, YONA-Automation/Yona-MobileAutomation/features/support/env.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/Signup.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/adddevice.rb
Added assertion for add device and singnup flows. Commiting changes to Git
=> Add Device and Singup

app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/message/MessageFragment.java, app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/java/nu/yona/app/utils/AppConstant.java
- App crash when clicking on step two - signup mobile number
- Listen API response for user not exist from any API response
- Handle title update for Notification
=> APPDEV-293

YONA-Automation/Yona-MobileAutomation/features/step_definitions/step_definition_add_challenges.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/add_challenges.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/common/common_UI_Functions.rb
Created a test script for NOGO challenge add and delete
=> Created a test script for NOGO

app/src/main/java/nu/yona/app/api/manager/NotificationManager.java, app/src/main/java/nu/yona/app/api/model/MessageBody.java, app/src/main/java/nu/yona/app/api/model/Properties.java, app/src/main/java/nu/yona/app/api/model/RegisterUser.java, app/src/main/java/nu/yona/app/api/model/YonaMessage.java, app/src/main/java/nu/yona/app/customview/YonaFontUtils.java, app/src/main/java/nu/yona/app/enums/IntentEnum.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsRequestFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OnFriendsItemClickListener.java, app/src/main/java/nu/yona/app/ui/message/MessageFragment.java, app/src/main/java/nu/yona/app/ui/message/MessageItemViewHolder.java, app/src/main/java/nu/yona/app/ui/message/MessageStickyRecyclerAdapter.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/drawable/button_accepter.xml, app/src/main/res/drawable/button_cancel.xml, app/src/main/res/layout/friend_request_layout.xml, app/src/main/res/layout/profile_fragment.xml, app/src/main/res/layout/profile_top_layout.xml, app/src/main/res/layout/user_message_item_layout.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Fixed : not able to see font bold,
Refactor code
=> [APPDEV-294] Friend Request Accept/Reject

app/src/main/java/nu/yona/app/api/manager/BuddyManager.java, app/src/main/java/nu/yona/app/api/manager/impl/BuddyManagerImpl.java, app/src/main/java/nu/yona/app/ui/message/MessageItemViewHolder.java, app/src/main/java/nu/yona/app/ui/message/MessageStickyRecyclerAdapter.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java, app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java
- Swipe delete and clickable event handle
- Friends: Delete friend
=> APPDEV-218

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Resend API with User call before OTP / verify PIN
=> Resend API with User

app/src/main/java/nu/yona/app/api/manager/AuthenticateManager.java, app/src/main/java/nu/yona/app/api/manager/BuddyManager.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/BuddyManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/ui/message/MessageItemViewHolder.java, app/src/main/java/nu/yona/app/ui/message/MessageStickyRecyclerAdapter.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java, app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java, app/src/main/java/nu/yona/app/ui/tour/CarrouselScroller.java, app/src/main/java/nu/yona/app/ui/tour/CarrouselViewPager.java, app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselActivity.java, app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselAdapter.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
yona:process Task on accept/reject
=> APPDEV-305

app/src/main/java/nu/yona/app/ui/settings/PrivacyFragment.java, app/src/main/res/layout/friend_request_layout.xml
Fixed: on Privacy page not validation enable (set Javascript enable)
=> Fixed: Friend Request page overlapping with notification page

app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/customview/CustomAlertDialog.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/challenges/BaseGoalCreateFragment.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselActivity.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
=> Added Snackbar

app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OverViewAdapter.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/pincode/YonaPasswordTransformationManager.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselActivity.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/drawable-hdpi/passcode_edit_bg_mango.xml, app/src/main/res/drawable/passcode_edit_bg_grape.xml, app/src/main/res/layout/blank_container_layout.xml, app/src/main/res/layout/pincode_layout.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml
- Dot is quite small - replace with *
- PIN reset should have opacity
=> APPDEV-236

YONA-Automation/Yona-MobileAutomation/features/SinguptoYona.feature, YONA-Automation/Yona-MobileAutomation/features/step_definitions/step_definition_add_challenges.rb, YONA-Automation/Yona-MobileAutomation/features/support/mobile/platform/capabilities.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/Signup.rb
=> Add Budget Goal

YONA-Automation/Yona-MobileAutomation/features/support/mobile/platform/android/inventory/sauce.yml, YONA-Automation/Yona-MobileAutomation/features/support/pages/add_challenges.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/common/common_UI_Functions.rb, YONA-Automation/Yona-MobileAutomation/features/support/settings/android.yml
=> Add Timzone Goal

YONA-Automation/Yona-MobileAutomation/features/step_definitions/Me_Profile.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/Profile.rb
=> Me-Profile View only

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/ui/Foreground.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
When user deletes a goal and in ongoing process minimizes app and comes back to the app, message is shown can not perform this action after onSaveInstanceState
=> APPDEV-268

YONA-Automation/Yona-MobileAutomation/features/SinguptoYona.feature, YONA-Automation/Yona-MobileAutomation/features/step_definitions/Me_Profile.rb, YONA-Automation/Yona-MobileAutomation/features/step_definitions/step_definition_add_challenges.rb, YONA-Automation/Yona-MobileAutomation/features/support/hooks.rb, YONA-Automation/Yona-MobileAutomation/features/support/mobile/platform/android/inventory/devices.yml, YONA-Automation/Yona-MobileAutomation/features/support/mobile/platform/capabilities.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/Profile.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/add_challenges.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/common/common_UI_Functions.rb
Refactored code for clock dial and swipe functions
=> Refactored code for clock dial and swipe functions

app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/res/layout/goal_detail_layout.xml, app/src/main/res/layout/timezoen_goal_item_layout.xml, app/src/main/res/values/integers.xml
Resolved Challenges scroll issue
=> Resolved Challenges scroll issue

app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java
Friend overview update on friend add
=> Friend overview update

YONA-Automation/Yona-MobileAutomation/features/support/mobile/platform/capabilities.rb
Changes for Integration with Jenkinsbuild with Sauce labs
=> Changes for Integration with Jenkinsbuild with Sauce labs

app/src/main/res/values-v21/styles.xml, app/src/main/res/values/styles.xml
=> Launch screen theme update

app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/ui/tour/CarrouselScroller.java, app/src/main/res/values-v21/styles.xml
removed status bar background to normal
=> Status bar background

app/src/main/java/nu/yona/app/ui/BaseActivity.java
Progress bar hide on minimise application
=> Progress bar hide on minimise application

app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
The Message has and extra Text with time shown.. EX. PT1 Min
When user Clicks on Pin Reset Button and The OTP is send..
The Message has and extra Text with time shown.. EX. PT1 Min
=> When user Clicks on Pin Reset Button and The OTP is send..

app/src/main/java/nu/yona/app/api/manager/PasscodeManager.java, app/src/main/java/nu/yona/app/api/manager/impl/PasscodeManagerImpl.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/res/anim/fade_in.xml, app/src/main/res/anim/fade_out.xml, app/src/main/res/layout/blank_container_layout.xml, app/src/main/res/layout/passcode_layout.xml
update UI for passcode screen,
change the color of Pinchange screen
=> Fixed: Passcode wrong entry not working correct

app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/res/layout/blank_container_layout.xml
Pin reset screen margin issue fixed
=> Pin reset screen margin issue fixed

app/src/main/java/nu/yona/app/api/model/Day.java, app/src/main/java/nu/yona/app/api/model/DayActivities.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/model/Embedded.java, app/src/main/java/nu/yona/app/api/model/EmbeddedDayActivityOverview.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaActivity.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/api/model/WeekActivity.java, app/src/main/java/nu/yona/app/api/model/YonaDayActivityOverview.java, app/src/main/java/nu/yona/app/api/model/YonaWeekActivityOverview.java
Create required POJO for activities/reports
=> Create required POJO for activities/reports

app/src/main/java/nu/yona/app/api/manager/APIManager.java, app/src/main/java/nu/yona/app/api/manager/ActivityManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/Day.java, app/src/main/java/nu/yona/app/api/model/DayActivities.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/model/Embedded.java, app/src/main/java/nu/yona/app/api/model/EmbeddedDayActivityOverview.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaActivity.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaUser.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/api/model/WeekActivity.java, app/src/main/java/nu/yona/app/api/model/YonaDayActivityOverview.java, app/src/main/java/nu/yona/app/api/model/YonaWeekActivityOverview.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/enums/StatusEnum.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/BaseActivity.java, app/src/main/java/nu/yona/app/ui/BaseFragment.java, app/src/main/java/nu/yona/app/ui/Foreground.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsRequestFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/ui/transition/DetailsTransition.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
API implementation for tracking report
=> APPDEV-373

YONA-Automation/Yona-MobileAutomation/features/SinguptoYona.feature, YONA-Automation/Yona-MobileAutomation/features/step_definitions/Me_Profile.rb, YONA-Automation/Yona-MobileAutomation/features/support/hooks.rb, YONA-Automation/Yona-MobileAutomation/features/support/mobile/platform/capabilities.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/Profile.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/Signup.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/add_challenges.rb, YONA-Automation/Yona-MobileAutomation/features/support/settings/android.yml, YONA-Automation/Yona-MobileAutomation/features/test.rb
Made changes to script to fix issues due to UI changes in Android buid 42
=> Script changes for APPDEV-321

YONA-Automation/Yona-MobileAutomation/features/step_definitions/Me_Profile.rb, YONA-Automation/Yona-MobileAutomation/features/step_definitions/step_definition_add_challenges.rb, YONA-Automation/Yona-MobileAutomation/features/support/hooks.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/add_challenges.rb
Make the application relaunch after each scenario execution
=> APPDEV-374

app/src/main/java/nu/yona/app/api/manager/APIManager.java, app/src/main/java/nu/yona/app/api/manager/AuthenticateManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityNetworkImpl.java, app/src/main/java/nu/yona/app/api/model/Embedded.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaActivity.java, app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/layout/spreading_chart_item.xml, app/src/main/res/layout/timebucket_chart_item.xml, app/src/main/res/layout/timeframe_chart_item.xml, app/src/main/res/values/dimens.xml
Create Time Bucket control handler
=> APPDEV-375

app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/enums/ChartTypeEnum.java, app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayStickyAdapter.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java, app/src/main/res/layout/dashboard_perday_fragment.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
=> APPDEV-376

app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/api/manager/AuthenticateManager.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaActivity.java, app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/enums/ChartTypeEnum.java, app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayStickyAdapter.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
Create background service to track application
=> APPDEV-377

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/model/YonaGoal.java
Create TimeFrame Raw data to use for Graph
=> APPDEV-379

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/model/Day.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/model/EmbeddedYonaActivity.java, app/src/main/java/nu/yona/app/api/model/WeekActivity.java, app/src/main/java/nu/yona/app/api/model/YonaGoal.java, app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekStickyAdapter.java, app/src/main/java/nu/yona/app/utils/DateUtility.java, app/src/main/res/layout/dashboard_perweek_fragment.xml, app/src/main/res/layout/week_chart_item.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
=> APPDEV-380

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayStickyAdapter.java
Added No Go Category for filter data.
=> Added No Go Category

app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayStickyAdapter.java
Add Click event on Me - Day list to go in detais of Time Bucket
=> APPDEV-390

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/ActivityManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/BuddyManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/DeviceManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/GoalManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/model/YonaGoal.java, app/src/main/java/nu/yona/app/customview/graph/BaseView.java, app/src/main/java/nu/yona/app/customview/graph/TimeFrameGraph.java, app/src/main/java/nu/yona/app/state/DataState.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsRequestFragment.java, app/src/main/java/nu/yona/app/ui/profile/BaseProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
- Keep loaded content of timeline to reuse during session.
=> Keep loaded content of timeline to reuse.

app/src/main/java/nu/yona/app/api/manager/ChallengesManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/enums/IntentEnum.java, app/src/main/java/nu/yona/app/state/DataState.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayStickyAdapter.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/layout/detail_activity_fragment.xml, app/src/main/res/layout/detail_pager_fragment.xml, app/src/main/res/layout/goal_chart_item.xml, app/src/main/res/layout/viewpager_fragment.xml, app/src/main/res/values/dimens.xml
=> APPDEV-391

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/state/DataState.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java
- update clear data on conditional way to keep loaded for detail fragment.
=> Flow issue

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/model/TimeZoneSpread.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayStickyAdapter.java
- sorting for sticky header
- removed duplicate entry from challenges after editing.
=> Sticky header sorting

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java
minor fix for update data after minimise
=> minor fix for update data after minimise

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/recyclerViewDecor/DividerDecoration.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java
- Data loading on minimise application
- Update user on application starts
=> Data Loading

app/src/main/java/nu/yona/app/api/manager/ChallengesManager.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/model/TimeZoneSpread.java, app/src/main/java/nu/yona/app/enums/IntentEnum.java, app/src/main/java/nu/yona/app/state/DataState.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/pincode/BasePasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/layout/dashboard_perday_fragment.xml, app/src/main/res/layout/dashboard_perweek_fragment.xml, app/src/main/res/layout/edit_profile_detail_fragment.xml, app/src/main/res/layout/friends_overview_fragment.xml, app/src/main/res/layout/friends_timeline_fragment.xml, app/src/main/res/layout/notification_layout.xml, app/src/main/res/layout/profile_fragment.xml
- Improved UI elements
- Added documentation
- removed unnecessary code.
=> Improved UI

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java
Implemented day detail page API for activities
=> Implemented day detail page API for activities

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/android-strings.xml, app/src/main/res/values/strings.xml
- API Update
- Change permission asking from LOLLIPOP
=> API Update

app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayStickyAdapter.java, app/src/main/res/layout/graph_top_info_layout.xml, app/src/main/res/layout/time_budget_item.xml, app/src/main/res/layout/time_frame_item.xml
Performance Improvement for Timeline
=> Performance Improvement for Timeline

app/src/main/java/nu/yona/app/api/manager/dao/ActivityTrackerDAO.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java, app/src/main/java/nu/yona/app/ui/pincode/BasePasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/res/layout/blank_container_layout.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml
- Android input PIN code - not a square
- Finish PIN activity on user not exist on server.
=> APPDEV-386

app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java
=> NoGo Graph load

app/src/main/java/nu/yona/app/customview/NestedListView.java, app/src/main/res/layout/goal_creation_layout.xml
Nested Goal scrolling issue resolved.
=> Nested Goal scrolling

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java
=> APPDEV-369

app/src/main/res/layout/passcode_layout.xml, app/src/main/res/values/styles.xml
=> Square box of passcode

app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml
Bottom margin added on Pinched
=> Bottom margin added

app/src/main/java/nu/yona/app/customview/graph/BaseView.java, app/src/main/java/nu/yona/app/customview/graph/SpreadGraph.java, app/src/main/java/nu/yona/app/customview/graph/TimeFrameGraph.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/res/layout/graph_top_info_layout.xml
Fixed Crash on profile page whille taping on edit button in htc
=> Fixed : Spread graph's bitmap not on center

app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/customview/NestedListView.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
App tracking:
- When screen on, start tracking
- When screen off, stop tracking
- Improved some code
=> App Tracking

app/src/main/java/nu/yona/app/api/db/DatabaseHelper.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java
Clear db and preferences on user unsubscribe from device.
=> Clear db and preference

app/src/main/java/nu/yona/app/ui/login/LoginActivity.java
=> Update data on Add device

app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/layout/nogo_chart_layout.xml, app/src/main/res/values-v21/styles.xml, app/src/main/res/values/styles.xml
Fixed not able to Type Capital D while registering user
=> Fixed Graph counter issue in

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/model/WeekActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekStickyAdapter.java
API changes for pagging
Changes for listing with header id.
Sorting of categories by name
=> APPDEV-451

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/api/model/WeekActivity.java
API implementation : week details for spread cells
=> APPDEV-453

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/model/WeekActivity.java, app/src/main/java/nu/yona/app/enums/IntentEnum.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekStickyAdapter.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/res/layout/detail_activity_fragment.xml
- Implementation paging for week detail control
=> APPDEV-454

app/src/main/java/nu/yona/app/api/db/DatabaseHelper.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/api/model/YonaDayActivityOverview.java, app/src/main/java/nu/yona/app/customview/NestedListView.java, app/src/main/java/nu/yona/app/customview/graph/CircleGraphView.java, app/src/main/java/nu/yona/app/customview/graph/GraphUtils.java, app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/java/nu/yona/app/utils/DateUtility.java
Create Model class for Friend timeline
=> APPDEV-461

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/enums/ChartTypeEnum.java, app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java
Time Frame control for week detail view
=> APPDEV-460

app/src/main/java/nu/yona/app/api/manager/ActivityManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/api/model/YonaDayActivityOverview.java, app/src/main/java/nu/yona/app/api/model/YonaGoal.java, app/src/main/java/nu/yona/app/customview/graph/BaseView.java, app/src/main/java/nu/yona/app/customview/graph/GraphUtils.java, app/src/main/java/nu/yona/app/enums/ChartTypeEnum.java, app/src/main/java/nu/yona/app/enums/IntentEnum.java, app/src/main/java/nu/yona/app/state/DataState.java, app/src/main/java/nu/yona/app/ui/ChartItemHolder.java, app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineFragment.java, app/src/main/java/nu/yona/app/utils/DateUtility.java
-API for friends
- Implementation of sticky list view
=> APPDEV-462

app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/model/YonaMessage.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/enums/StatusEnum.java
Handled Notification for goals
=> Handled Notification for goals

app/build.gradle, app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/BuddyManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/DeviceManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/GoalManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/PasscodeManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/api/manager/network/GoalNetworkImpl.java, app/src/main/java/nu/yona/app/api/model/SecureKey.java, app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/security/BaseSecurity.java, app/src/main/java/nu/yona/app/security/DecryptUser.java, app/src/main/java/nu/yona/app/security/EncryptUser.java, app/src/main/java/nu/yona/app/security/GenerateKeys.java, app/src/main/java/nu/yona/app/state/DataState.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/state/SharedPreference.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselActivity.java, app/src/test/java/nu/yona/app/api/manager/impl/PasscodeManagerImplTest.java
Implemented RSA to encrypt yoga password before store.
=> Implemented RSA

app/src/main/java/nu/yona/app/api/db/DatabaseHelper.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java
On unregister, application crashing issue resolved.
=> APPDEV-464

app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/res/layout/nogo_chart_layout.xml
=> Week Detail Control

app/build.gradle
Reverted OS version support to make compatible with Jenkins
=> Jenkins configuration update

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/DeviceManagerImpl.java, app/src/main/java/nu/yona/app/state/SharedPreference.java
Added encryption for add device
=> Encryption for Add device

app/src/main/java/nu/yona/app/security/BaseSecurity.java, app/src/main/java/nu/yona/app/security/DecryptUser.java, app/src/main/java/nu/yona/app/security/EncryptUser.java, app/src/main/java/nu/yona/app/security/GenerateKeys.java
implemented AES algorithm for M+ OS
=> Implemented AES

app/src/main/java/nu/yona/app/api/manager/BuddyManager.java, app/src/main/java/nu/yona/app/api/manager/impl/BuddyManagerImpl.java, app/src/main/java/nu/yona/app/api/model/YonaMessage.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/state/SharedPreference.java, app/src/main/java/nu/yona/app/ui/BaseActivity.java, app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java
Removing friend issue resolved
=> APPDEV-472

app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineFragment.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java, app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java
- on Adding or removing friend, list should update.
- Requested friend should not view friend's timeline.
=> Friend Add/Remove

app/src/main/java/nu/yona/app/api/model/DayActivities.java, app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
=> Strings update

app/src/main/java/nu/yona/app/customview/CustomProgressDialog.java, app/src/main/java/nu/yona/app/ui/BaseActivity.java, app/src/main/res/drawable/progressbar_background.xml, app/src/main/res/layout/progressbar_dialog_layout.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml
as not using text and button on loading so, removed that part
=> [APPDEV-477] Update Loading indicator

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/db/JsonSerializer.java, app/src/main/java/nu/yona/app/api/manager/ActivityManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/model/BaseEntity.java, app/src/main/java/nu/yona/app/api/model/YonaHeaderTheme.java, app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/security/MyCipher.java, app/src/main/java/nu/yona/app/state/SharedPreference.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineFragment.java, app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselActivity.java, app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselAdapter.java, app/src/main/java/nu/yona/app/utils/DateUtility.java
Improvement in code and error handling
=> APPDEV-415

app/src/main/java/nu/yona/app/api/manager/ActivityManager.java, app/src/main/java/nu/yona/app/api/manager/NotificationManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/NotificationNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/DayActivity.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/api/model/YonaMessage.java, app/src/main/java/nu/yona/app/enums/NotificationEnum.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java
Get Comments from server for day activity
=> APPDEV-478

app/src/main/java/nu/yona/app/api/manager/ActivityManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Handle Friend's comment notification
When friend comment on any day/week activity, user get notification in notification area.
=> APPDEV-493

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/state/SharedPreference.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java
- Add device encryption handle
- Handle crash scenario in day detail page
- Change in color theme
=> APPDEV-221

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java
-On tab click, user come back to home page of tab from any level of hierarchy.
- Week detail control day starts from sunny.
=> Tab selection improvement

app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/layout/dashboard_perday_fragment.xml, app/src/main/res/layout/dashboard_perweek_fragment.xml, app/src/main/res/layout/detail_activity_fragment.xml, app/src/main/res/layout/week_chart_item.xml, app/src/main/res/layout/week_score_control_layout.xml
Scrolling issue:
- last item was showing partial in list.
- Exception handling was giving error.
=> APPDEV-428

app/src/main/java/nu/yona/app/api/manager/ActivityManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/Message.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java
add comment API implementation
=> APPDEV-499

app/src/main/java/nu/yona/app/api/model/BaseEntity.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/frinends/SingleDayActivityDetailFragment.java, app/src/main/res/layout/comment_box.xml, app/src/main/res/layout/detail_pager_fragment.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Add comment box at end of page
- it should only be visible when user is on friend's timeline challenge
- Or user get comment from friend and user can allow to reply there.
=> APPDEV-496

app/src/main/res/layout/pin_toolbar.xml, app/src/main/res/layout/toolbar.xml, app/src/main/res/layout/toolbar_layout.xml, app/src/main/res/values/dimens.xml
padding bottom on title , its not same (look into detail page , setting page)
=> APPDEV-476

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java, app/src/main/res/layout/comment_box.xml
=> APPDEV-500

app/src/main/java/nu/yona/app/api/model/AddBuddy.java, app/src/main/java/nu/yona/app/api/model/AppActivity.java, app/src/main/java/nu/yona/app/api/model/Buddy.java, app/src/main/java/nu/yona/app/api/model/EmbeddedDayActivityOverview.java, app/src/main/java/nu/yona/app/api/model/Message.java, app/src/main/java/nu/yona/app/api/model/NewDeviceRequest.java, app/src/main/java/nu/yona/app/api/model/Page.java, app/src/main/java/nu/yona/app/api/model/PinResetDelay.java, app/src/main/java/nu/yona/app/api/model/PostYonaGoal.java, app/src/main/java/nu/yona/app/api/model/Properties.java, app/src/main/java/nu/yona/app/api/model/YonaDayActivityOverview.java, app/src/main/java/nu/yona/app/api/model/YonaMessages.java, app/src/main/java/nu/yona/app/api/model/YonaWeekActivityOverview.java, app/src/main/java/nu/yona/app/customview/graph/TimeFrameGraph.java
=> TimeFrameGraph not populated correct

app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/api/manager/AuthenticateManager.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselActivity.java
Deep linking to handle mail url to register.
=> APPDEV-517

app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java
If user is unsubscribes and Registers again with some other number without killing the app No user found error is shown in API
If User unsubscribes and then clicks android back button then the pin screen appears and upon entering pin no user found error is shown
=> Unsubscribe issues

app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/res/layout/horizontal_line_view.xml
- Update data on resuming application
=> Data update on reopening app

YONA-Automation/Yona-MobileAutomation/features/1SinguptoYona.feature, YONA-Automation/Yona-MobileAutomation/features/5profile.feature, YONA-Automation/Yona-MobileAutomation/features/AddFriend.feature, YONA-Automation/Yona-MobileAutomation/features/FriendProfile.feature, YONA-Automation/Yona-MobileAutomation/features/PinReset.feature, YONA-Automation/Yona-MobileAutomation/features/step_definitions/Me_Profile.rb, YONA-Automation/Yona-MobileAutomation/features/step_definitions/step_definition_Unsubscribe.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/Profile.rb, YONA-Automation/Yona-MobileAutomation/features/support/pages/Signup.rb, YONA-Automation/Yona-MobileAutomation/features/test.feature, YONA-Automation/Yona-MobileAutomation/features/test.rb
=> Me profile edit done

app/src/main/java/nu/yona/app/customview/YonaFontEditTextView.java, app/src/main/java/nu/yona/app/customview/YonaFontNumberTextView.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/res/layout/add_friend_manually_fragment.xml, app/src/main/res/layout/login_activity.xml, app/src/main/res/layout/passcode_layout.xml, app/src/main/res/layout/profile_details_view.xml, app/src/main/res/layout/signup_steptwo_fragment.xml
=> APPDEV-384

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
=> APPDEV-525

app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values/strings.xml, openvpn/src/main/java/de/blinkt/openvpn/activities/DisconnectVPN.java
=> APPDEV-549

app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
=> Changes in strings

openvpn/build.gradle
configuration changes to work openvpn with Jenkins
=> configuration changes

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java
Error decrypting data error is shown on PIN reset
=> APPDEV-542

app/src/main/java/nu/yona/app/ui/YonaActivity.java
Behaviour not proper after user unsubscribes from one device and uses in another device
=> APPDEV-543

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/res/values/strings.xml, openvpn/src/main/java/de/blinkt/openvpn/LaunchVPN.java
=> APPDEV-539

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsRequestFragment.java
Fixed user friend's profileImage not getting update while going from notification
=> Fixed Crash on Displaying dialogue

app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml, openvpn/src/main/java/de/blinkt/openvpn/activities/ConfigConverter.java
=> Language Translation

app/src/main/java/nu/yona/app/api/db/DatabaseHelper.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java
=> Hockey app bug fixing

app/src/main/res/values/strings.xml
=> APPDEV-553

app/src/main/java/nu/yona/app/api/manager/impl/ActivityCategoryManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java
Resolved some hockey app issues
=> Hockey app issue

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityCategoriesNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BuddyNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/DeviceNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/GoalNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/NotificationNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java
Added Language Translation Header
=> Language Translation Header

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineFragment.java
=> Fixed Crash

app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java
Language translation argument changes
=> Language translation argument changes

app/src/main/java/nu/yona/app/utils/DateUtility.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Week Date issue: Date starts incorrectly when data of more than 2 weeks.
=> Week Date issue

app/src/main/java/nu/yona/app/api/manager/network/ActivityCategoriesNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/ActivityNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BuddyNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/DeviceNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/GoalNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/NotificationNetworkImpl.java
=> Local changes

app/src/main/java/nu/yona/app/ui/frinends/FriendsRequestFragment.java
Update bottom tab on friend request received
=> Tab Update

app/build.gradle, app/src/zuat/res/values/bool.xml, app/src/zuat/res/values/strings.xml
Added UAT flavor for HockeyApp
=> UAT Flavor

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java
Dashboard - duplicate entries in Day view
=> APPDEV-558

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java
java.lang.String nu.yona.app.api.model.YonaActivityCategories.getName()
=> java.lang.String nu.yona.app.api.model.YonaActivityCategories.getName()

app/src/main/java/nu/yona/app/ui/frinends/OverViewAdapter.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Friends overview - Requested friends
=> APPDEV-574

Architecture.md, README.md
=> Added readme

app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
During signup (join me screen), no spaces allowed in Firstname and Lastname
=> APPDEV-565

app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
=> APPDEV-588

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineFragment.java
When switching apps back to Yona, timeline of friends is empty
=> APPDEV-560

app/src/main/java/nu/yona/app/ui/tour/CarrouselViewPager.java, app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselActivity.java
Images add welcome screen not working properly
=> APPDEV-590

app/src/main/java/nu/yona/app/api/model/YonaMessage.java, app/src/main/java/nu/yona/app/utils/DateUtility.java
Friend Activities - Weekview --> Strange dates
=> APPDEV-578

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/state/DataState.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java
Send-code-again button doesn't work
=> APPDEV-567

app/src/main/java/nu/yona/app/api/db/DatabaseHelper.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java
=> DB clear issue

app/src/main/java/nu/yona/app/api/manager/NotificationManager.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/model/Links.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OnFriendsItemClickListener.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java, app/src/main/java/nu/yona/app/ui/message/MessageItemViewHolder.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java, app/src/main/java/nu/yona/app/ui/profile/ProfileFragment.java
Send read status to server for messages
=> APPDEV-648

app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/res/layout/toolbar_layout.xml
Touch area increase for properly touch
=> APPDEV-537

app/src/main/java/nu/yona/app/customview/YonaFontEditTextView.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
User is shown Login screen when user accesses Phonebook
=> APPDEV-624

app/src/main/java/nu/yona/app/customview/graph/TimeFrameGraph.java
White line appears When user uses any app during specified time in timezone
=> APPDEV-626

app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java
Your friend declines your invite - nickname appearance
=> APPDEV-576

app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/ui/message/MessageStickyRecyclerAdapter.java
Decline Notification - missing Decline Icon
=> APPDEV-573

app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java
App crashes when user minimizes app and Come back to the App
=> APPDEV-657

app/src/main/java/nu/yona/app/ui/pincode/BasePasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
During sign up when user enters incorrect pin on "Confirm Pin" screen, implementation is not matching acceptance criteria.
=> APPDEV-160

app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java
Sometime re-launching the app user is not asked to enter the pin
=> APPDEV-658

app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java
=> APPDEV-650

app/src/main/java/nu/yona/app/api/model/User.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
Root Certificate name for parsing and comparing on device
=> APPDEV-669

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/ui/BaseActivity.java
Bugs found in Build #75 on hockey app analytics.
=> Hockey Bug fixing

app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java
Add Profile Picture  -Android - complete implementation after server side ready
=> APPDEV-622

app/src/main/res/layout/toolbar_layout.xml, app/src/main/res/values/dimens.xml
=> APPDEV-659

app/src/main/res/layout/comment_box.xml, app/src/main/res/values/dimens.xml
The send button is not big enough as per the zeplin design
=> APPDEV-479

app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java
App Crashes When user Changes Language of device
=> APPDEV-674

app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java
Mobile phone number not getting displayed in Friends profile
=> APPDEV-673

app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/ui/frinends/SingleDayActivityDetailFragment.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
App crashes when user trys to disconnect VPN
+ Other hockey app issues
=> APPDEV-680

app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java
Activity Category Not getting filtered
=> APPDEV-679

app/src/zuat/res/values/strings.xml
=> Updated UAT url for jenkins

app/src/main/java/nu/yona/app/api/manager/impl/ActivityCategoryManagerImpl.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java
Resolved crashes found in hockey app
=> Resolved crashes found in hockey app

app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java
Nogo notification should take user in detail page
=> APPDEV-579

app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java
On the me page after looking at a challenge and pressing the back button the dashboard text changes to the text of the last visited challenge
=> APPDEV-682

app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/res/layout/signup_stepone_fragment.xml, app/src/main/res/values/colors.xml
Join me screen - header not properly positioned.
=> APPDEV-566

app/src/main/java/nu/yona/app/ui/pincode/BasePasscodeActivity.java
The 5-Pincode page title doesn't match the design
=> APPDEV-683

app/build.gradle, app/src/main/java/nu/yona/app/ui/comment/CommentsAdapter.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/SingleWeekDayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OverViewAdapter.java, app/src/main/java/nu/yona/app/ui/frinends/SingleDayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineStickyAdapter.java, app/src/main/java/nu/yona/app/ui/message/MessageStickyRecyclerAdapter.java, app/src/main/java/nu/yona/app/ui/profile/BaseProfileFragment.java, app/src/main/java/nu/yona/app/utils/ColorGenerator.java, app/src/main/java/nu/yona/app/utils/TextDrawable.java, app/src/main/res/layout/profile_fragment.xml, app/src/main/res/layout/profile_top_layout.xml, app/src/main/res/layout/viewpager_fragment.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/integers.xml
=> APPDEV-536

app/src/main/java/nu/yona/app/ui/frinends/AddFriendFragment.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
UI does not match on Add friend page
=> APPDEV-709

app/src/main/java/nu/yona/app/ui/challenges/BaseGoalCreateFragment.java, app/src/main/java/nu/yona/app/ui/challenges/CreditFragment.java, app/src/main/java/nu/yona/app/ui/challenges/NoGoFragment.java, app/src/main/java/nu/yona/app/ui/challenges/ZoneFragment.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Android wrong text on challenge timezone and bucket
=> APPDEV-703

app/src/main/java/nu/yona/app/ui/dashboard/CustomPageAdapter.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayStickyAdapter.java, app/src/main/res/layout/graph_top_info_layout.xml
Android wrong text on timezone label
=> APPDEV-705

app/src/main/java/nu/yona/app/ui/challenges/ChallengesFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendFragment.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsFragment.java, app/src/main/res/layout/custom_tab_layout.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
As per discussion with Bastiaan, set tab bar height as 46 dp for all pages.
=> Tab Bar Height

app/src/main/java/nu/yona/app/customview/graph/GraphUtils.java, app/src/main/java/nu/yona/app/customview/graph/TimeFrameGraph.java, app/src/main/java/nu/yona/app/utils/TextDrawable.java, app/src/main/res/values/dimens.xml
Android Friend timeline UI issues
=> APPDEV-545

app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/pincode/BasePasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PinActivity.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/java/nu/yona/app/utils/PreferenceConstant.java, app/src/main/res/layout/blank_container_layout.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Android Timer function after PIN reset
=> APPDEV-392

app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml, libTimepicker/src/main/res/values-nl/strings.xml
=> APPDEV-416

app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/res/layout/custom_tab_layout.xml, app/src/main/res/layout/goal_detail_layout.xml, app/src/main/res/layout/header_challenges.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml
=> APPDEV-532

app/src/main/java/nu/yona/app/customview/CustomAlertDialog.java, app/src/main/java/nu/yona/app/customview/graph/TimeBucketGraph.java, app/src/main/res/layout/timeframe_graph_layout.xml, app/src/main/res/values/dimens.xml
Android UI issues on Me day overview
=> APPDEV-541

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/customview/graph/BaseView.java, app/src/main/java/nu/yona/app/customview/graph/GraphUtils.java, app/src/main/java/nu/yona/app/customview/graph/SpreadGraph.java, app/src/main/java/nu/yona/app/customview/graph/TimeFrameGraph.java, app/src/main/res/layout/detail_activity_fragment.xml
Android Activity view UI issues
=> APPDEV-534 - Android Activity view UI issues

app/src/main/java/nu/yona/app/customview/graph/SpreadGraph.java, app/src/main/res/drawable/comment_background.xml, app/src/main/res/drawable/edit_text_cursor.xml, app/src/main/res/layout/comment_box.xml, app/src/main/res/layout/comment_layout.xml, app/src/main/res/layout/parent_message_item.xml, app/src/main/res/values/dimens.xml
=> APPDEV-700

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/challenges/NoGoFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/frinends/FriendsFragment.java, app/src/main/java/nu/yona/app/ui/frinends/OverviewFragment.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineFragment.java
Sometimes on Me-Timeline, page appears blank.
=> APPDEV-729

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/utils/TextDrawable.java
UI not proper of Activity Detail page while viewing from Friends timeline
=> APPDEV-739

app/src/main/java/nu/yona/app/ui/message/MessageStickyRecyclerAdapter.java
Friend fullname in Notifications
=> APPDEV-736

app/src/main/java/nu/yona/app/api/model/RegisterUser.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Add number friend from address book
=> APPDEV-734

app/src/main/java/nu/yona/app/ui/frinends/FriendsFragment.java
Android Add friend button missing on friends timeline
=> APPDEV-701

app/src/main/java/nu/yona/app/ui/frinends/OverViewAdapter.java
Friend Accepts - Firstname shown instead of Nickname
=> APPDEV-577

app/src/main/java/nu/yona/app/ui/YonaActivity.java
Getting Url Not Found Error and Application Keeps asking to install CA certificate
=> APPDEV-738

app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java
Holding down the backspace button stop deleting when hitting a space or the first character of the field
=> APPDEV-661

app/src/main/java/nu/yona/app/customview/YonaFontNumberTextView.java, app/src/main/java/nu/yona/app/state/EventChangeManager.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java
Backspace not working on login screen
=> APPDEV-108

app/src/main/java/nu/yona/app/ui/message/MessageItemViewHolder.java, app/src/main/res/layout/user_message_item_layout.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Ui Not matching for Notifications
=> APPDEV-755

app/src/main/java/nu/yona/app/ui/comment/CommentHolder.java, app/src/main/java/nu/yona/app/ui/comment/CommentsAdapter.java, app/src/main/res/layout/child_message_item.xml, app/src/main/res/layout/comment_layout.xml, app/src/main/res/layout/parent_message_item.xml, app/src/main/res/values-nl/strings.xml
Comment UI issue for margins and alignment
=> Comment UI issue

app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java
Wierd behaviour when backspace is Clicked on Login screen
=> APPDEV-773

app/src/main/java/nu/yona/app/customview/graph/TimeBucketGraph.java
Digits Getting Cut on Me-Timeline and Friends Timeline
=> APPDEV-771

app/build.gradle, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/res/layout/settings_fragment.xml
=> updated version

app/src/main/java/nu/yona/app/analytics/YonaAnalytics.java, app/src/main/res/values-nl/strings.xml
Android Comment shows untranslated reply link
=> APPDEV-803

app/src/main/java/nu/yona/app/api/manager/ActivityManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/ui/frinends/SingleDayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/message/MessageStickyRecyclerAdapter.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java, app/src/main/java/nu/yona/app/utils/AppConstant.java
Header title missing from NOGO Details page
=> APPDEV-715

app/src/main/AndroidManifest.xml
Android Active input field (mobile number) not visible at add friend.
=> APPDEV-814

app/src/main/java/nu/yona/app/analytics/AnalyticsConstant.java, app/src/main/java/nu/yona/app/ui/pincode/BasePasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java
=> Analytics string changes

app/build.gradle
updated application version code to 5
=> Change Version Code

app/build.gradle, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/User.java, app/src/main/java/nu/yona/app/enums/NotificationEnum.java, app/src/main/java/nu/yona/app/enums/NotificationMessageEnum.java, app/src/main/java/nu/yona/app/state/SharedPreference.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml, app/src/zproduction/res/values/strings.xml, build.gradle, libTimepicker/build.gradle, openvpn/build.gradle
Password generation at Server - Android
=> APPDEV-1001

app/src/main/java/nu/yona/app/ui/frinends/OverViewAdapter.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineStickyAdapter.java
=> APPDEV-1002

app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
=> APPDEV-992

app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java
=> APPDEV-1012

app/src/main/java/nu/yona/app/ui/YonaActivity.java
VPN installation delayed on Android
=> APPDEV-1027

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/api/manager/dao/ActivityTrackerDAO.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/pincode/PasscodeFragment.java, app/src/main/res/values/strings.xml, app/src/zproduction/res/values/strings.xml
We are not able to pass the "Enter verification code" screen after reinstalling the app - RESOLVED.
=> APPDEV-1048

app/src/main/java/nu/yona/app/ui/tour/YonaCarrouselActivity.java
Swipe to the right two times in the welcome screen the third slide will become "blank"
Signed-off-by: Punit Sharma <psharma@mobiquityinc.com>
=> APPDEV-618

app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java
Invalid app activity data: end time is before start time
Signed-off-by: Punit Sharma <psharma@mobiquityinc.com>
=> APPDEV-929

app/src/main/java/nu/yona/app/ui/comment/CommentsAdapter.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java
=> APPDEV-1014

app/src/main/java/nu/yona/app/ui/comment/CommentsAdapter.java
App crashes after sending or open the received messages
=> APPDEV-1051

app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/BuddyManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/DeviceManagerImpl.java, app/src/main/java/nu/yona/app/customview/YonaPhoneWatcher.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/java/nu/yona/app/ui/login/LoginActivity.java, app/src/main/java/nu/yona/app/ui/profile/DetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/res/layout/add_friend_manually_fragment.xml, app/src/main/res/layout/login_activity.xml, app/src/main/res/layout/profile_details_view.xml, app/src/main/res/layout/signup_steptwo_fragment.xml, app/src/main/res/values/integers.xml, gradle/wrapper/gradle-wrapper.properties
Android - Prefix mobile phone field should be editable
Signed-off-by: Punit Sharma <psharma@mobiquityinc.com>
=> APPDEV-1007

app/src/main/java/nu/yona/app/ui/frinends/TimelineFragment.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Oeps er is iets misgegaan
Signed-off-by: Punit Sharma <psharma@mobiquityinc.com>
=> APPDEV-1030

app/src/main/java/nu/yona/app/api/model/YonaActivityCategories.java, app/src/main/java/nu/yona/app/ui/challenges/ChallengesGoalDetailFragment.java, app/src/main/res/layout/footer_challenges_layout.xml
Displaying description messgae receiving from server instead of package name. Reference Ticket: Yona/APPDEV-857.
=> Display description instead of package name.

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/api/manager/AuthenticateManager.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/api/model/YonaBuddy.java, app/src/main/java/nu/yona/app/api/utils/ServerErrorCode.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/signup/OTPActivity.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/main/java/nu/yona/app/ui/signup/StepOne.java, app/src/main/java/nu/yona/app/ui/signup/StepTwo.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/java/nu/yona/app/utils/Logger.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml, app/src/zacceptance/res/values/strings.xml, app/src/zdev/res/values/strings.xml, app/src/zdevelopment/res/values/strings.xml, app/src/zproduction/res/values/strings.xml, app/src/zuat/res/values/strings.xml
Following issue we worke on for this commit:
APPDEV-818: (Link in email friend invite not working): Done.
APPDEV-821: (Impossible to go back to input phone number while creating account): Done
APPDEV-999: (Historical data disappears when I change my challenge): In-Progress.
APPDEV-1025: (Adult Alert on Android): Previously Done.
APPDEV-1026: (Wrong mobile phone number during installation on Android): Done.
APPDEV-1050: (Oeps er is iets misgegaan during registration): Handle cases. In case not then it will be display system error message.
=> Fix multiple issue: Deep link, Sign Up back button issue and few more.

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/BuddyManagerImpl.java, app/src/main/java/nu/yona/app/api/model/YonaBuddy.java, app/src/main/java/nu/yona/app/enums/NotificationEnum.java, app/src/main/java/nu/yona/app/ui/frinends/AddFriendManually.java, app/src/main/java/nu/yona/app/ui/frinends/OverViewAdapter.java, app/src/main/java/nu/yona/app/ui/frinends/TimelineFragment.java, app/src/main/java/nu/yona/app/ui/message/MessageStickyRecyclerAdapter.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/java/nu/yona/app/utils/DateUtility.java, app/src/main/res/layout/add_friend_manually_fragment.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml, app/src/zacceptance/res/values/strings.xml
Following summy of issue fixes in this commit.
APPDEV-1055: Mobile number validation. Added internatoionalisation support.
APPDEV-1054: Update Local based String text.
APPDEV-999: HistoryData Loss fix. #isHistory validation.
APPDEV-1057: Last seen date. Added Date formating support.
APPDEV-1000: System support message support update.
=> Multiple issue fixes.

app/src/main/res/layout/admin_notification_fragment.xml, app/src/main/res/values/dimens.xml
Increase size of pop-up and set parent backgound to look it nice.
Task Reference: http://jira.yona.nu/browse/APPDEV-1000
=> FIx: Issue display issuew for Admin message detail page.

app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/Logger.java, openvpn/src/main/res/values/strings.xml
Note: Added test component to debug JIRA_1022 which is related with applicaiton performace.
Observation: Applicaiton perform History upload API call for each start irrespective if data is recorded or not.
=> [Debug] JIRA_1022-App Performance.

app/src/main/java/nu/yona/app/ui/YonaActivity.java, openvpn/src/main/res/values/strings.xml
Note: This must be revert back before to market release.
=> [Update] available 1022_debug code for release build. #Testing.

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/db/DatabaseHelper.java, app/src/main/java/nu/yona/app/api/manager/dao/ActivityTrackerDAO.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/security/PRNGFixes.java, app/src/main/java/nu/yona/app/ui/BaseActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/java/nu/yona/app/utils/DownloadFileFromURL.java, libTimepicker/src/main/java/nu/yona/timepicker/time/CircleView.java, openvpn/src/main/java/de/blinkt/openvpn/LaunchVPN.java
=> [Fix] Multiple receiver registeration.

app/build.gradle, app/fabric.properties, app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/YonaApplication.java, app/src/zacceptance/res/values/bool.xml, app/src/zdev/res/values/bool.xml, app/src/zdevelopment/res/values/bool.xml, app/src/zproduction/res/values/bool.xml, app/src/zuat/res/values/bool.xml, app/src/zuat/res/values/integers.xml, build.gradle
revert c30af719129d74109364ecf0ec2a9c69e9dd3259
=> Remove fabric

app/src/development/res/values/bool.xml, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/production/res/values/bool.xml
-- Removed the boolean constant "allowEnvironmentSwitch"  to enable the feature.
=> APPDEV-1069 Environment Switch enabled for production mode also.

app/src/main/java/nu/yona/app/ui/YonaActivity.java
- Added Build flavour check for VPN alert.
- Replaced userPreferences usages across file. This need to be done in entire application over time.
=> APPDEV-1154 Remove VPN connection alert in production

app/build.gradle, app/src/main/java/nu/yona/app/enums/EncryptionMethod.java, app/src/main/java/nu/yona/app/security/CryptoProvider.java, app/src/main/java/nu/yona/app/security/MyCipher.java, app/src/main/java/nu/yona/app/state/SharedPreference.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/java/nu/yona/app/utils/PreferenceConstant.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml, libTimepicker/build.gradle, openvpn/build.gradle
- Incremented Android Target Version to 26.
- Updated the Password Encryption Functionality.
- Functionality to automatically change re-encrypt the old yona password in user preferences with new Encryption function.
=> APPDEV-1135 increase target sdk version to 26

Jenkinsfile, app/fastlane/Fastfile
* Added the required stages
* Uncommented the lane
Along with this:
* Move the logic for incrementing the version number into a function
* Extended the commit message with the version code
* Switched from "deploy" and "promote" to "release", in alignment with the terminology on Google Play
=> APPDEV-1161 Enable app release to production

app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java
-- Added null check for embedded yonaMessages object from response.
=> APPDEV-1171 Crash on Android 5.1

app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java
-- Fixed a crash caused by refactored ErrorMessage class.
=> APPDEV-1174 Crash Fix when clicked on friends tab.

app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
-- This is happening when device goes to doze mode. To fix this, added device_awake alarm broadcast for starting foreground service. This fires only after device goes into doze mode and OS above OREO.
=> APPDEV-1196 App activity monitoring notification disappears.

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
-- Added extra logging to find root cause.
=> APPDEV-1197 Vpn does not connect.

app/src/main/AndroidManifest.xml
Removed the permission from manifest.
=> APPDEV-1224 Remove SMS permission request in the application.

app/src/main/java/nu/yona/app/ui/frinends/TimelineStickyAdapter.java
-- Setting the tag to list item holder view to differentiate the header and other views in.
-- Minor code refactoring.
APPDEV-1223 - Crash in header-- Adding reference to duplicate ticket.
=> APPDEV-1225 Fabric reported crash in TimelineFragment 

app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java
- Fixed an issue where profile picture is not reflecting upon updating it.
- Refactored EditDetailsProfileFragment.java class
=> APPDEV-1218 Profile pic update issue

app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Fixed exception when disconnecting VPN manually.
-- Updated Notification builder with Notification channel needed for OREO and above.
-- Added null check for Notification Pending Intent. Suspect for Null pointer exception.
=> APPDEV-1219 Fabric Exceptoin in build 5.

app/src/main/java/nu/yona/app/ui/BaseFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java
-Fixed issue
-Refactoring of DayActivityDetailFragment.java
=> APPDEV-1209 comments are displayed twice in single day activity view

app/src/main/java/nu/yona/app/ui/BaseFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java
-Fixed the issue
-Refactoring of WeekActivityDetailFragment.java
=> APPDEV-1210 comments are displayed twice in single week activity overview

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
- Fixed the issue
- Now the alert for enabling the notification permission will shown on app launch
=> APPDEV-1230 Fabric Fatal Exceptions on Build-13(175)

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/state/DataState.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
-- Corrected the Preferences Initialization which went wrong in previous commits. Due to which App was unable to recognize the already logged in user. 
This bug was introduced in APPDEV-1222.
=> APPDEV-1239 lost account. Issue since APPDEV-1222

app/src/main/java/nu/yona/app/ui/pincode/BasePasscodeActivity.java
- Added a null check for the errorMessage object.
- Now app will show the alert only if the activity is present.
=> APPDEV-1226 Farbic crash in build 11 171

app/src/main/java/nu/yona/app/ui/friends/TimelineFragment.java
-Fixed the issue that caused a crash in Friends Timeline after adding a new friend.
-Code refactoring of TimelineFragment.java
=> APPDEV-1247 Fabric crash in build (7) (11) (13)

app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java
- Added App version, app build, android version, device brand and model.
- Now yona password will be added to support mail upon user acceptance.
=> APPDEV-1234 Added app version info to support request mail

app/src/main/java/nu/yona/app/ui/LaunchActivity.java
-- Moving User entity version check after validating the https scheme.
=> APPDEV-1256 Minor correction in Develop after merge from Master.

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/analytics/YonaAnalytics.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/ChallengesManagerImpl.java, app/src/main/java/nu/yona/app/api/model/User.java, app/src/main/java/nu/yona/app/api/model/YonaDevice.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/SingleDayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/SingleWeekDayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
-Updated the code to take vpn profile from the device entity rather than the user
-Added a getter for user object from local db.
-Minor refactoring of AppUtils.java
=> APPDEV-1110 take the vpn profile from the device entity rather than the user

app/src/main/java/nu/yona/app/api/model/YonaBuddy.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
Minor changes to Logger. All exceptions will be logged in crashlytics even when reported in UI.
=> APPDEV-1255 npe in friends timeline

app/src/main/java/nu/yona/app/ui/friends/TimelineFragment.java
=> APPDEV-1250 Scroll issue in timeline after adding a new goal

app/src/main/java/nu/yona/app/ui/pincode/BasePasscodeActivity.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
-disabled back action in pin reset
-updated the code to show correct timer at pin reset screen.
-refactoring of BasePasscodeActivity.java
-added an alert upon clicking pin reset button
=> APPDEV-1240 disable back action in pin reset screen

app/src/main/java/nu/yona/app/api/db/DBConstant.java, app/src/main/java/nu/yona/app/api/manager/dao/ActivityTrackerDAO.java, app/src/main/java/nu/yona/app/api/manager/dao/BaseDAO.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
- App posts list of accumulated App activities to server in batches with batch size configurable(currently 200).
- Deletes the posted batch before sending next batch.
=> APPDEV-1238 app accumulates too much app activity

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
Updated language for Alert message text.
=> APPDEV 1265 fabric crash on build 26(206) in huawei device

app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
- App now checks if device has usage access permissions active on device, if not alerts the user
=> APPDEV-1265 fabric crash on build 26(206) in huawei device

app/src/main/java/nu/yona/app/ui/YonaActivity.java
Issue: App is closed and user is taken to Device home screen.
-- App now takes user to Dashboard. Proper fix would be to bring back user to same screen. But that needs a lot of efforts to fetch all needed data from server.
-- Minor refactoring.
=> APPDEV-1227 UI issue in Day and week detail screens, when app is launched from recents.

app/src/main/AndroidManifest.xml, app/src/main/java/nu/yona/app/api/receiver/YonaReceiver.java, app/src/main/java/nu/yona/app/api/service/ActivityMonitorService.java, app/src/main/java/nu/yona/app/utils/AppConstant.java, app/src/main/java/nu/yona/app/utils/AppUtils.java
-- Vpn notification icon updated as mentioned in appdev-1237
-- On click of notification, it will be dismissed and app will try to connect to VPN again.
-- Notification is be cancellable (swipe to cancel).
-- If user ignores it and launches app, notification will be dismissed.
=> APPDEV-1267 VPN Disconnect Notification icon changes

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/AuthenticateManager.java, app/src/main/java/nu/yona/app/api/manager/impl/ActivityManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/BuddyManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/DeviceManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/GoalManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/impl/NotificationManagerImpl.java, app/src/main/java/nu/yona/app/api/manager/network/AuthenticateNetworkImpl.java, app/src/main/java/nu/yona/app/api/manager/network/BaseImpl.java, app/src/main/java/nu/yona/app/api/manager/network/RestApi.java, app/src/main/java/nu/yona/app/state/DataState.java, app/src/main/java/nu/yona/app/state/SharedPreference.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/comment/CommentsAdapter.java, app/src/main/java/nu/yona/app/ui/dashboard/DashboardFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/DayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerDayFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/PerWeekFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/SingleDayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/SingleWeekDayActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/dashboard/WeekActivityDetailFragment.java, app/src/main/java/nu/yona/app/ui/friends/TimelineFragment.java, app/src/main/java/nu/yona/app/ui/message/NotificationFragment.java, app/src/main/java/nu/yona/app/ui/pincode/BasePasscodeActivity.java, app/src/main/java/nu/yona/app/ui/profile/BaseProfileFragment.java, app/src/main/java/nu/yona/app/ui/profile/EditDetailsProfileFragment.java, app/src/main/java/nu/yona/app/ui/signup/SignupActivity.java, app/src/test/java/nu/yona/app/api/manager/impl/AuthenticateManagerImplTest.java
-- App now properly clears cache when user unsubscribes and registers again.
-- Refactoring for authentication flow (Regitstartion, update user detials).
-- Removed long constructs for global user data.
=> APPDEV-1268 Issue with user reg after un subscribing

app/src/main/java/nu/yona/app/YonaApplication.java, app/src/main/java/nu/yona/app/api/manager/impl/AuthenticateManagerImpl.java, app/src/main/java/nu/yona/app/ui/LaunchActivity.java, app/src/main/java/nu/yona/app/ui/YonaActivity.java, app/src/main/java/nu/yona/app/ui/settings/SettingsFragment.java, app/src/main/java/nu/yona/app/utils/AppUtils.java, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
APPDEV-1269 Vpn and yona service to be stopped after un-subscribing.
-- App now disconnects the VPN connection after successful un-subscribing at server end. Post to that app clears local cached user data and preferences.
=> APPDEV-1269 Vpn and yona service to be stopped after unsubscribing.
